package net.dnns.giessy.torch.model;

/**
 * Created by Tincho on 2/28/2017.
 */

public class Province {

    public static final String[] AR = {"Buenos Aires ", "Buenos Aires F.D. ", "Catamarca ", "Chaco ", "Chubut ", "Cordoba ", "Corrientes ", "Entre Rios ", "Formosa ", "Jujuy ", "La Pampa ", "La Rioja ", "Mendoza ", "Misiones ", "Neuquen ", "Rio Negro ", "Salta", "San Juan", "San Luis", "Santa Cruz", "Santa Fe", "Santiago del Estero", "Tierra del Fuego", "Tucuman"};
    public static final String[] BR = {"Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Espírito Santo", "Federal District", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Paraná", "Paraíba", "Pará", "Pernambuco", "Piauí", "Rio Grande do Norte", "Rio Grande do Sul", "Rio de Janeiro", "Rondônia", "Roraima", "Santa Catarina", "Sergipe", "São Paulo", "Tocantins"};
    public static final String[] CA = {"Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Northwest Territories", "Nova Scotia", "Nunavut", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan", "Yukon"};
    public static final String[] FR = {"Auvergne-Rhône-Alpes", "Bourgogne-Franche-Comté", "Brittany", "Centre", "Corsica", "Grand-Est", "Hauts-de-France", "Normandy", "Nouvelle-Aquitaine", "Occitanie", "Pays de la Loire", "Provence-Alpes-Côte d'Azur", "Île-de-France"};
    public static final String[] IT = {"Abruzzo", "Aosta Valley", "Apulia", "Basilicate", "Calabria", "Campania", "Emilia-Romagna", "Friuli Venezia Giulia", "Latium", "Liguria", "Lombardy", "Molise", "Piedmont", "Sardinia", "Sicily", "The Marches", "Trentino-Alto Adige", "Tuscany", "Umbria", "Veneto"};
    public static final String[] JP = {"Aichi", "Akita", "Aomori", "Chiba", "Ehime", "Fukui", "Fukuoka", "Fukushima", "Gifu", "Gunma", "Hiroshima", "Hokkaido", "Hyōgo", "Ibaraki", "Ishikawa", "Iwate", "Kagawa", "Kagoshima", "Kanagawa", "Kochi", "Kumamoto", "Kyoto", "Mie", "Miyagi", "Miyazaki", "Nagano", "Nagasaki", "Nara", "Niigata", "Oita", "Okayama", "Okinawa", "Saga", "Saitama", "Shiga", "Shimane", "Shizuoka", "Tochigi", "Tokushima", "Tokyo", "Tottori", "Toyama", "Wakayama", "Yamagata", "Yamaguchi", "Yamanashi", "Ōsaka"};
    public static final String[] UK = {"Barnsley", "Bath and North East Somerset", "Bedford", "Birmingham", "Blackburn with Darwen", "Blackpool", "Bolton", "Borough of Bury", "Bournemouth", "Bracknell Forest", "Bradford", "Brighton and Hove", "Bristol", "Buckinghamshire", "Calderdale", "Cambridgeshire", "Central Bedfordshire", "Cheshire", "Cheshire East", "Cornwall", "Coventry", "Cumbria", "Darlington", "Derby", "Derbyshire", "Devon", "Doncaster", "Dorset", "Dudley", "Durham", "East Sussex", "East Yorkshire", "Essex", "Gateshead", "Gloucestershire", "Greater London", "Halton", "Hampshire", "Hartlepool", "Herefordshire", "Hertfordshire", "Isle of Wight", "Isles of Scilly", "Kent", "Kingston upon Hull", "Kirklees", "Knowsley", "Lancashire", "Leeds", "Leicester", "Leicestershire", "Lincolnshire", "Liverpool", "Luton", "Manchester", "Medway", "Middlesbrough", "Milton Keynes", "Newcastle upon Tyne", "Norfolk", "North East Lincolnshire", "North Lincolnshire", "North Somerset", "North Tyneside", "North Yorkshire", "Northamptonshire", "Northumberland", "Nottingham", "Nottinghamshire", "Oldham", "Oxfordshire", "Peterborough", "Plymouth", "Poole", "Portsmouth", "Reading", "Redcar and Cleveland", "Rochdale", "Rotherham", "Rutland", "Salford", "Sandwell", "Sefton", "Sheffield", "Shropshire", "Slough", "Solihull", "Somerset", "South Gloucestershire", "South Tyneside", "Southampton", "Southend-on-Sea", "St. Helens", "Staffordshire", "Stockport", "Stockton-on-Tees", "Stoke-on-Trent", "Suffolk", "Sunderland", "Surrey", "Swindon", "Tameside", "Telford and Wrekin", "Thurrock", "Torbay", "Trafford", "Wakefield", "Walsall", "Warrington", "Warwickshire", "West Berkshire", "West Sussex", "Wigan", "Wiltshire", "Windsor and Maidenhead", "Wirral", "Wokingham", "Wolverhampton", "Worcestershire", "York"};
    public static final String[] US = {"Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "Washington, D.C.", "West Virginia", "Wisconsin", "Wyoming"};
}
